services:
  - type: web
    name: memoryscribe
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WTF_CSRF_ENABLED
        value: true
      - key: FLASK_ENV
        value: production
