"""Augmenter taille colonnes password_hash et api_key_encrypted

Revision ID: a984d1c7a42c
Revises: 
Create Date: 2025-01-06 14:14:31.377045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a984d1c7a42c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Augmenter la taille des colonnes à 512 caractères
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('api_key_encrypted',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Revenir aux tailles d'origine
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('api_key_encrypted',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
